const fs=require('fs'),path=require('path'),matter=require('gray-matter'),{marked}=require('marked');
const root=__dirname,dist=path.join(root,'dist'); fs.rmSync(dist,{recursive:true,force:true}); fs.mkdirSync(dist,{recursive:true});
function cp(src,dst){if(!fs.existsSync(src))return;fs.cpSync(src,dst,{recursive:true})} cp(path.join(root,'assets'),path.join(dist,'assets'));cp(path.join(root,'admin'),path.join(dist,'admin'));
const base='https://local-divorce-guide.netlify.app';
function shell(title,desc,body,canonical){return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${desc}"><link rel="canonical" href="${canonical}"><meta property="og:url" content="${canonical}"><link rel="stylesheet" href="/assets/style.css"></head><body><header><div class="wrap"><a class="brand" href="/">지역이혼정보안내</a></div></header>${body}<footer><div class="wrap">지역별 이혼 절차와 준비사항 안내</div></footer></body></html>`}
const posts=[];for(const f of fs.readdirSync(path.join(root,'content/posts')).filter(x=>x.endsWith('.md'))){const p=matter(fs.readFileSync(path.join(root,'content/posts',f),'utf8'));posts.push({...p.data,html:marked.parse(p.content)});}
for(const p of posts){const dir=path.join(dist,p.province,p.city);fs.mkdirSync(dir,{recursive:true});const url=`${base}/${p.province}/${p.city}/`;fs.writeFileSync(path.join(dir,'index.html'),shell(p.title,p.description,`<main><section class="hero"><div class="wrap"><h1>${p.title}</h1><p class="lead">${p.description}</p></div></section><article class="wrap"><div class="card">${p.html}</div></article></main>`,url));}
const links=posts.map(p=>`<a href="/${p.province}/${p.city}/">${p.region}</a>`).join('');fs.writeFileSync(path.join(dist,'index.html'),shell('지역이혼정보안내 | 지역별 이혼 준비정보','지역별 이혼 절차와 준비사항을 정리한 정보 사이트입니다.',`<main><section class="hero"><div class="wrap"><h1>지역별 이혼 절차와 준비사항 안내</h1><p class="lead">협의·조정·재판 절차부터 재산과 자녀 문제까지 지역별로 확인하세요.</p></div></section><section class="wrap"><div class="regions">${links}</div></section></main>`,base+'/'));
const seoul=posts.filter(p=>p.province==='seoul');fs.mkdirSync(path.join(dist,'seoul'),{recursive:true});fs.writeFileSync(path.join(dist,'seoul','index.html'),shell('서울 이혼 준비정보 | 지역이혼정보안내','서울 지역별 이혼 준비정보 안내',`<main><section class="hero"><div class="wrap"><h1>서울 이혼 준비정보</h1></div></section><section class="wrap"><div class="regions">${seoul.map(p=>`<a href="/seoul/${p.city}/">${p.region}</a>`).join('')}</div></section></main>`,base+'/seoul/'));
fs.writeFileSync(path.join(dist,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);const urls=[base+'/',base+'/seoul/',...posts.map(p=>`${base}/${p.province}/${p.city}/`)];fs.writeFileSync(path.join(dist,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${u}</loc></url>`).join('')}</urlset>`);
